### ISSUE TITLE
'Connection to server lost' after in-game login form.

### ISSUE THREAD

**Issue by stley** [juce/fiveserver#19]
Hello, i recently cloned this repo on my VPS and i managed to set it up.
The thing is, after creating my account, i went in-game and tried to log-in. Moments after filling the log-in form with my serial, and username-password and pressing connect, the game returns with a 'Connection to server lost' error.

![image](https://user-images.githubusercontent.com/57237098/179579965-ff37b041-82db-4f04-88ac-fa32ccb23095.png)

Here I drop you the last 30 lines of the log:

```
2022-07-18T15:37:44-0300` [NewsProtocol,2,179.39.180.172] Unhandled Error
	Traceback (most recent call last):
	  File "/home/fiveserver/.local/lib/python3.7/site-packages/twisted/python/log.py", line 96, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/fiveserver/.local/lib/python3.7/site-packages/twisted/python/log.py", line 80, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/fiveserver/.local/lib/python3.7/site-packages/twisted/python/context.py", line 117, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/fiveserver/.local/lib/python3.7/site-packages/twisted/python/context.py", line 82, in callWithContext
	    return func(*args, **kw)
	--- <exception caught here> ---
	  File "/home/fiveserver/.local/lib/python3.7/site-packages/twisted/internet/posixbase.py", line 683, in _doReadOrWrite
	    why = selectable.doRead()
	  File "/home/fiveserver/.local/lib/python3.7/site-packages/twisted/internet/tcp.py", line 248, in doRead
	    return self._dataReceived(data)
	  File "/home/fiveserver/.local/lib/python3.7/site-packages/twisted/internet/tcp.py", line 253, in _dataReceived
	    rval = self.protocol.dataReceived(data)
	  File "/home/fiveserver/lib/fiveserver/protocol/__init__.py", line 55, in dataReceived
	    self._packetReceived(pkt)
	  File "/home/fiveserver/lib/fiveserver/protocol/__init__.py", line 88, in _packetReceived
	    self.packetReceived(pkt)
	  File "/home/fiveserver/lib/fiveserver/protocol/__init__.py", line 141, in packetReceived
	    return handler(pkt)
	  File "/home/fiveserver/lib/fiveserver/protocol/pes6.py", line 100, in getServerList_2005
	    struct.pack('!H',d)) for a,b,name,ip,port,c,d in servers])
	  File "/home/fiveserver/lib/fiveserver/protocol/pes6.py", line 100, in <listcomp>
	    struct.pack('!H',d)) for a,b,name,ip,port,c,d in servers])
	builtins.AttributeError: 'NoneType' object has no attribute 'encode'
	
2022-07-18T15:37:44-0300 [NewsProtocol,2,179.39.180.172] Connection lost: 'NoneType' object has no attribute 'encode'
```

Do you have any clue about how do I fix this error?
Thank you.

**Comment by ToniFabri** [comment]
Imput you IP in sixserver.yml

**Comment by arnon001** [comment]
Its not working for me 2

**Comment by windflash-cloud** [comment]
I had the same problem

**Comment by EXCIDIVM** [comment]
Same issue here. I can enter my credentials, and it also gives me a different error if I enter the wrong credentials.
But after that I get a "connection to server lost" error.

**Comment by estibenlicona** [comment]
Were they able to fix?

**Comment by moth1995** [comment]
@stley @estibenlicona @EXCIDIVM @windflash-cloud @arnon001 if you guys could provide some information or add this line of code on pes6.py around line 92

```
        print(f"servers: {servers}")
```

reload the server and do the same to check the logs again, this way it will provide more information of the value that its failing and getting into None, but by reading some previous comments probably its the serverIp so you might have to set the ip manually because autodetection is failing

**Comment by WagnerSami** [comment]
Acredito que seja por não possui IP fixo nesse caso única forma é usar IP do radmin ou ramachi... Configurando arquivo config.py IP Lan (IP do seu computador) IP wan (ip do seu Radmin ou fixo)e 
seversix.yaml caso funciona sem precisa alterar IP deixa auto mesmo...
