### ISSUE TITLE
Error starting the 'sixserver' service service.sh

### ISSUE THREAD

**Issue by eatornini** [juce/fiveserver#22]
"Hello friend, thank you for your project. When attempting to start the sixserver service via 'service service.sh,' I'm encountering the following error. It seems to be a compatibility issue with Python3. I would appreciate it if you could guide me on how to resolve this problem. Thank you very much."

`Unhandled Error
Traceback (most recent call last):
  File "/root/fiveserver/.local/lib/python3.11/site-packages/twisted/application/app.py", line 674, in run
    runApp(config)
  File "/root/fiveserver/.local/lib/python3.11/site-packages/twisted/scripts/twistd.py", line 29, in runApp
    runner.run()
  File "/root/fiveserver/.local/lib/python3.11/site-packages/twisted/application/app.py", line 370, in run
    self.application = self.createOrGetApplication()
  File "/root/fiveserver/.local/lib/python3.11/site-packages/twisted/application/app.py", line 437, in createOrGetApplication
    application = getApplication(self.config, passphrase)
--- <exception caught here> ---
  File "/root/fiveserver/.local/lib/python3.11/site-packages/twisted/application/app.py", line 446, in getApplication
    application = service.loadApplication(filename, style, passphrase)
  File "/root/fiveserver/.local/lib/python3.11/site-packages/twisted/application/service.py", line 404, in loadApplication
    application = sob.loadValueFromFile(filename, "application")
  File "/root/fiveserver/.local/lib/python3.11/site-packages/twisted/persisted/sob.py", line 177, in loadValueFromFile
    eval(codeObj, d, d)
  File "./tac/sixserver.tac", line 15, in <module>
    from fiveserver.protocol import pes5, pes6
  File "/root/fiveserver/lib/fiveserver/protocol/pes5.py", line 9, in <module>
    from Crypto.Cipher import Blowfish
  File "/root/fiveserver/.local/lib/python3.11/site-packages/Crypto/Cipher/Blowfish.py", line 120, in <module>
    key_size = xrange(4,56+1)
builtins.NameError: name 'xrange' is not defined

Failed to load application: name 'xrange' is not defined`

**Comment by pedroh14** [comment]
> "Olá amigo, obrigado pelo seu projeto. Ao tentar iniciar o serviço sixserver via 'service service.sh', estou encontrando o seguinte erro. Parece ser um problema de compatibilidade com Python3. Eu agradeceria se você pudesse oriente-me sobre como resolver este problema. Muito obrigado."
> 
> ` Traceback de erro não tratado (última chamada mais recente): Arquivo "/root/fiveserver/.local/lib/python3.11/site-packages/twisted/application/app.py", linha 674, no arquivo run runApp (config) "/root/fiveserver/.local/lib/python3.11/site-packages/twisted/scripts/twistd.py", linha 29, no arquivo runApp runner.run() "/root/fiveserver/.local/lib/ python3.11/site-packages/twisted/application/app.py", linha 370, em run self.application = self.createOrGetApplication() Arquivo "/root/fiveserver/.local/lib/python3.11/site-packages /twisted/application/app.py", linha 437, em createOrGetApplication application = getApplication(self.config, passphrase) --- --- Arquivo "/root/fiveserver/.local/lib/python3.11/site-packages /twisted/application/app.py", linha 446, em getApplication application = service.loadApplication(filename, style, passphrase) Arquivo "/root/fiveserver/.local/lib/python3.11/site-packages/twisted/application /service.py", linha 404, em loadApplication application = sob.loadValueFromFile(filename, "application") Arquivo "/root/fiveserver/.local/lib/python3.11/site-packages/twisted/persisted/sob.py ", linha 177, em loadValueFromFile eval(codeObj, d, d) Arquivo "./tac/sixserver.tac", linha 15, em from fiveserver.protocol import pes5, pes6 Arquivo "/root/fiveserver/lib/fiveserver/protocol /pes5.py", linha 9, em Crypto.Cipher import Blowfish File "/root/fiveserver/.local/lib/python3.11/site-packages/Crypto/Cipher/Blowfish.py", linha 120, em key_size = xrange(4,56+1) builtins.NameError: o nome 'xrange' não está definido
> 
> Falha ao carregar o aplicativo: o nome 'xrange' não está definido`

I solved this problem by doing the following:

enter the indicated file using a text editor in my case I used nano. look for the indicated line (line 120) you will need to make a simple change from "xrange" to "range"
